[package]
name = "zryna-architecture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
same-file.workspace = true
toml.workspace = true
zryna-diagnostics = { path = "../zryna-diagnostics" }

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[lints]
workspace = true
