[package]
name = "uts-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
uts-diagnostics = { path = "../uts-diagnostics" }
uts-source = { path = "../uts-source" }

[lints]
workspace = true
