[workspace]
resolver = "2"
members = [
  "apps/zryna",
  "crates/zryna-abi",
  "crates/zryna-architecture",
  "crates/zryna-backend-javascript",
  "crates/zryna-backend-native",
  "crates/zryna-backend-webassembly",
  "crates/zryna-diagnostics",
  "crates/zryna-driver",
  "crates/zryna-frontend",
  "crates/zryna-ir",
  "crates/zryna-native-mir",
  "crates/zryna-semantics",
  "crates/zryna-source",
  "crates/zryna-syntax",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"
repository = "https://github.com/zryna/zryna"
homepage = "https://zryna.com"
authors = ["Aditya Nandlal"]

[workspace.dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
cranelift-codegen = { version = "=0.135.1", default-features = false, features = ["std", "x86"] }
cranelift-frontend = { version = "=0.135.1", default-features = false, features = ["std"] }
cranelift-module = { version = "=0.135.1", default-features = false, features = ["std"] }
cranelift-object = { version = "=0.135.1", default-features = false }
libc = "0.2"
nix = { version = "=0.31.3", default-features = false, features = ["process", "signal"] }
object = { version = "=0.39.0", default-features = false, features = ["read_core", "elf", "std"] }
process-wrap = { version = "=10.0.0", default-features = false, features = ["process-group", "std"] }
same-file = "1.0.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha2 = "=0.10.9"
thiserror = "2.0.16"
toml = "0.9.5"
target-lexicon = "=0.13.5"
windows-spawn = "=0.1.0"
wasm-encoder = { version = "=0.258.0", default-features = false, features = ["std"] }
wasmparser = { version = "=0.258.0", default-features = false, features = ["features", "std", "validate"] }
zryna-abi = { path = "crates/zryna-abi" }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
rust_2018_idioms = { level = "deny", priority = -1 }
unused_lifetimes = "deny"
unused_qualifications = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
