[package]
name = "zryna-frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zryna-diagnostics = { path = "../zryna-diagnostics" }
zryna-source = { path = "../zryna-source" }
zryna-syntax = { path = "../zryna-syntax" }

[target.'cfg(unix)'.dependencies]
nix.workspace = true
process-wrap.workspace = true

[target.'cfg(windows)'.dependencies]
windows-spawn.workspace = true

[lints]
workspace = true

[[test]]
name = "worker_process"
path = "tests/worker_process.rs"
harness = false
