[package]
name = "zryna-backend-webassembly"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sha2.workspace = true
wasm-encoder.workspace = true
wasmparser.workspace = true
wit-component.workspace = true
wit-parser.workspace = true
zryna-diagnostics = { path = "../zryna-diagnostics" }
zryna-ir = { path = "../zryna-ir" }
zryna-layout = { path = "../zryna-layout" }
zryna-ownership-runtime-abi = { path = "../zryna-ownership-runtime-abi" }

[dev-dependencies]
zryna-source = { path = "../zryna-source" }
zryna-semantics = { path = "../zryna-semantics" }
zryna-syntax = { path = "../zryna-syntax" }
serde_json.workspace = true

[lints]
workspace = true
