[package]
name = "zryna-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
zryna-abi.workspace = true
zryna-diagnostics = { path = "../zryna-diagnostics" }
zryna-layout = { path = "../zryna-layout" }
zryna-ownership-runtime-abi = { path = "../zryna-ownership-runtime-abi" }
zryna-source = { path = "../zryna-source" }
zryna-syntax = { path = "../zryna-syntax" }

[lints]
workspace = true
