[package]
name = "zryna-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
zryna-diagnostics = { path = "../zryna-diagnostics" }
zryna-source = { path = "../zryna-source" }

[lints]
workspace = true
