[package]
name = "zryna"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "zryna"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
zryna-architecture = { path = "../../crates/zryna-architecture" }
zryna-diagnostics = { path = "../../crates/zryna-diagnostics" }
zryna-driver = { path = "../../crates/zryna-driver" }

[lints]
workspace = true
