[package]
name = "uts-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "uts"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
uts-architecture = { path = "../../crates/uts-architecture" }
uts-diagnostics = { path = "../../crates/uts-diagnostics" }
uts-driver = { path = "../../crates/uts-driver" }

[lints]
workspace = true
