[package]
name = "uts-backend-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
uts-diagnostics = { path = "../uts-diagnostics" }
uts-native-mir = { path = "../uts-native-mir" }

[lints]
workspace = true
