[package]
name = "zryna-backend-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zryna-diagnostics = { path = "../zryna-diagnostics" }
zryna-native-mir = { path = "../zryna-native-mir" }

[lints]
workspace = true
