[package]
name = "zryna-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libc.workspace = true
nix.workspace = true
object.workspace = true
process-wrap.workspace = true
zryna-abi.workspace = true
zryna-architecture = { path = "../zryna-architecture" }
zryna-backend-javascript = { path = "../zryna-backend-javascript" }
zryna-backend-native = { path = "../zryna-backend-native" }
zryna-backend-webassembly = { path = "../zryna-backend-webassembly" }
zryna-diagnostics = { path = "../zryna-diagnostics" }
zryna-frontend = { path = "../zryna-frontend" }
zryna-ir = { path = "../zryna-ir" }
zryna-native-mir = { path = "../zryna-native-mir" }
zryna-semantics = { path = "../zryna-semantics" }
zryna-source = { path = "../zryna-source" }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
