[package]
name = "zryna-semantics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zryna-abi.workspace = true
zryna-diagnostics = { path = "../zryna-diagnostics" }
zryna-ir = { path = "../zryna-ir" }
zryna-layout = { path = "../zryna-layout" }
zryna-source = { path = "../zryna-source" }
zryna-syntax = { path = "../zryna-syntax" }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
