[package]
name = "zryna-layout"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sha2.workspace = true
zryna-diagnostics = { path = "../zryna-diagnostics" }
zryna-source = { path = "../zryna-source" }

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
